### ISSUE TITLE
Add Instruction about Allowing unauthenticated function invocation

### ISSUE THREAD

**Issue by yayinchang** [actions-on-google/dialogflow-interactive-canvas-codelab-nodejs#1]
I was running this codelab and being stuck in **Step 4 - Connect the web app to the Assistant** for hours.
When I tried to test my Action in simulator after making sure everything has set up correctly, including Firebase Functions URL for Webhook, I kept receiving this error:
```
MalformedResponse
Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: db5040ba-3070-446e-8b86-5fc603999df3 and intentId: df333e1d-586b-4bc2-b3a2-b77296a4a6e5. WebhookStatus: code: 2 message: "Webhook call failed. Error: UNKNOWN." ..
```
And when I tried to access my function, it turned out to be 403 Forbidden:
![Screen Shot 2020-04-28 at 11 11 16 AM](https://user-images.githubusercontent.com/10168831/80443151-24b5df80-8941-11ea-93b3-dec847fbd7e2.png)

After hours of searching, I finally found the [official doc](https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation) indicating the changing:

> Note: As of January 15, 2020, HTTP functions require authentication by default. You can specify whether a function allows unauthenticated invocation at or after deployment.

Perhaps adding this instruction in the codelab for learners who are new to Actions on Google and Google Cloud?

**Comment by Fleker** [comment]
Which version of Firebase CLI are you using? I believe that, using the latest version, it should automatically set the authorization of functions to be public even with the policy changing.

**Comment by om-mega** [comment]
Even after changing policy, I am unable to test the action.

_Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: f1d0072e-ec87-4c27-9e3d-e837e49def33 and intentId: df333e1d-586b-4bc2-b3a2-b77296a4a6e5. WebhookStatus: code: 5 message: "Webhook call failed. Error: NOT_FOUND." .._

**Comment by Fleker** [comment]
If I `curl` that URL I end up getting an expected response. I would double-check that you've entered the correct URL in your Dialogflow Fulfillment section.
